#!/usr/bin/env python
# -*- mode: python; coding: utf-8; -*-

"""Script for predicting polarity classes of tweets.

The input file is assumed to be in TSV format where the second field
(starting with 0) is assumed to be the gold label and the last field
contains the text of the messages.

USAGE:
twitter_sentiment [MODE] [OPTIONS] [input_file]

@author = Wladimir Sidorenko (Uladzimir Sidarenka)
@mail = <sidarenk at uni dash potsdam dot de>
@version = 0.0.1

"""

##################################################################
# Imports
from __future__ import print_function, unicode_literals

from sentiment_classifier import SentimentClassifier
from evaluate import evaluate, get_fields, GLD_IDX, TXT_IDX
from twokenize import tokenize

import argparse
import sys

##################################################################
# Variables and Constants
TRAIN = "train"
TEST = "test"
EVALUATE = "evaluate"

TAB = "\t"

##################################################################
# Methods
def _add_cmn_options(a_parser):
    """Add common options to option subparser

    @param a_parser - option subparser

    @return \c void

    """
    a_parser.add_argument("-m", "--model", help = "path to the (stored or to be stored) model", \
                              type = str)
    a_parser.add_argument("files", help = "input files in TSV format", \
                              type = argparse.FileType('r'), nargs = '*', default = [sys.stdin])

def _iterlines(a_file):
    """Iterate over input lines of a file

    @param a_file - input file to iterate over

    @return iterator over resulting TSV fields

    """
    for iline in a_file:
        # compute prediction and append it to the list of fields
        yield get_fields(iline)

def main():
    """Classify tweets according to their sentiment polarity

    @return \c 0 on success, non-0 other
    """
    # process CLI arguments
    argparser = argparse.ArgumentParser(description = """Script for classifying
tweets according to their sentiment polarity""")

    subparsers = argparser.add_subparsers(help="type of operation to perform", dest = "mode")
    # training options
    tr_parser = subparsers.add_parser(TRAIN, help = "train the model")
    _add_cmn_options(tr_parser)
    # testing options
    test_parser = subparsers.add_parser(TEST, help = "test the model")
    test_parser.add_argument("-v", "--verbose", help = "output scores along with predicted labels",
                             action = "store_true")
    _add_cmn_options(test_parser)
    # evaluation options (train and test at the same time)
    ev_parser = subparsers.add_parser(EVALUATE, help = "evaluate trained model")
    _add_cmn_options(ev_parser)
    ev_parser.add_argument("-v", "--verbose", help = "output errors along with evaluation",
                           action = "store_true")
    args = argparser.parse_args()
    # perform the requied action
    if args.mode == TRAIN:
        classifier = SentimentClassifier(a_path = None)
        classifier.train([([list(w) for w in tokenize(ifields[TXT_IDX])], ifields[GLD_IDX]) \
                          for ifile in args.files \
                          for ifields in _iterlines(ifile)], a_path = args.model)
    elif args.mode == TEST:
        # load model from default location
        y = ""; score = 0.
        classifier = SentimentClassifier()
        for ifile in args.files:
            for ifields in _iterlines(ifile):
                y, score = classifier.predict([list(w) for w in tokenize(ifields[TXT_IDX])])
                if args.verbose:
                    ifields.append(str(score))
                ifields.append(y)
                print(TAB.join(ifields))
    else:
        raise NotImplementedError
        # for ifile in a_files:
        #     macro_MAE, micro_MAE = evaluate(classify(classifier, ifile), args.verbose, lambda x: x)
        #     print("{:20s}{:.7}".format("Macro-averaged MAE:", macro_MAE), file = sys.stderr)
        #     print("{:20s}{:.7}".format("Micro-averaged MAE:", micro_MAE), file = sys.stderr)
    return 0

##################################################################
# Main
if __name__ == "__main__":
    main()
